### ISSUE TITLE
ДЗ 5.2

### ISSUE THREAD

**Issue by Aloren** [KulekSasha/calculatorSpring#1]
1. Почему Calculator prototype? 
https://github.com/KulekSasha/calculatorSpring/blob/master/src/main/java/com/sk/config/AppConfig.java
2. Попробуй вместо:
```
calculator.setSupportedOperations(getDefaultOperations());
getNotDefaultOperations().forEach(o -> calculator.addToSupportedOperations(o));
````
вот так:
```
public Calculator getCalculator(List<Operation> operations) {
...
calculator.setSupportedOperations(operations);
```
https://github.com/KulekSasha/calculatorSpring/blob/master/src/main/java/com/sk/config/AppConfig.java
Должно сработать.

**Comment by KulekSasha** [comment]
1. Следовал совету - As a rule, use the prototype scope for all state-full beans and the singleton scope for stateless beans. [Tutorialspoint](http://www.tutorialspoint.com/spring/spring_bean_scopes.htm). Мой калькулятор  state-full (при условии если кто-то добавит еще одну/несколько операций)

2. Переменную в конструкторе назвал не _operations_, а _defaultOperations_, т.к. спринг не мог определить, что передать в конструктор (default или notDefault).
